# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71e6fe7075f16f51bd0bffd96ade1ad17d84910bc83fb1080608224309b3f3b34b5a350abd86343859a85da72a61952b1bbdff4cd2a4c6ecc825b7fd26461b1a

test:
  secret_key_base: 14c6dcd01076b0cd76972d301944b5440251e59eaed5af34ebf78d15a375e7a94fd0e77651e030af7c648f44dbfe2acb673d2542aa8bb36c5d583059d3b27d61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
